### ISSUE TITLE
bigWig as input

### ISSUE THREAD

**Issue by oleraj** [pbenner/modhmm#1]
Hi, 

I saw your talk at RECOMB, very nice.  I'm interested in getting ModHMM data for Human cell types and at the ENCODE project they have bigWig files available for many cell types.  Would it be possible to optionally support bigWig files as input for this tool?  For the imputed datasets [here](https://egg2.wustl.edu/roadmap/data/byFileType/signal/consolidatedImputed/), bigWig is the only format available.

Thanks,

Andrew

**Comment by pbenner** [comment]
Dear Andrew,
We have already computed segmentations for several human cell types (ENCODE data), I will upload them as soon as possible. ModHMM also accepts bigWigs as input, but the enrichment analysis step (single-feature analysis) so far expects (discrete) count data, whereas the imputed bigWigs seem to contain p-values. I will look into that.
Best,
Philipp

**Comment by oleraj** [comment]
Great to know you already have segmentations for some human ENCODE data.  And thanks for looking into the bigWig files.

**Comment by pbenner** [comment]
Hi Andrew,
I've uploaded 10 segmentations for human data and improved the usability of modhmm. The new version should allow you to use ENCODE imputed bigWigs. By default modhmm applies a quantile normalization, which will basically restore the count data. How bigWigs can be used as input is now described in the README. Let me know if you have any issues.
Best,
Philipp
