### ISSUE TITLE
H3K36me3 vs RNA-seq

### ISSUE THREAD

**Issue by jessakay** [pbenner/modhmm#2]
I'm very interested in trying your method as an alternative to ChromHMM, but unfortunately we have only 3' RNA-seq data. Would it be possible to use H3K36me3 data in lieu of whole transcript RNA-seq?

**Comment by pbenner** [comment]
No, at the moment it is not possible to use H3K36me3 instead of RNA-seq. In my experience the H3K36me3 signal is too weak to make reliable inferences about transcribed genes, which ModHMM uses in certain cases to distinguish between promoters and enhancers.

**Comment by jessakay** [comment]
Ah okay I see. Thanks for the quick response.
