### ISSUE TITLE
Requirement of individual target tracks

### ISSUE THREAD

**Issue by michaelbale** [pbenner/modhmm#3]
Hello, I'm very interested in utilizing this software; however, I would be missing data tracks for H3K9me3. It looks like on the README that K9me3 is not required? Is this correct, or do all tracks need to be present?

**Comment by pbenner** [comment]
Dear Michael,
Features H3K27me3, H3K9me3, and Control are optional and you can simply leave them empty in the config file if you don't have them.
Best regards,
Philipp

**Comment by michaelbale** [comment]
Thank you so much! Looking forward to using this software!
